// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1747775493);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1747776771);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1747773531);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1747775344);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1747773291);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1747775373);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1747773201);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1747775613);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 33295);
user_pref("browser.cache.disk.capacity", 890880);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1747773141);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{03f60d0f-4493-45f9-bd4d-52c365dda0cb}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1747778912387");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1747780741387");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1747773147414");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1747794747414");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200602222727");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1747775344");
user_pref("browser.slowStartup.averageTime", 1571);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1747775343);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1747773144221");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "b3dcc3dff28d4e8a99a6cd70e2dfce11");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1747775493);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200602222727");
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"092d9814-a842-4174-87b9-31c8435e7857\",\"formautofill@mozilla.org\":\"23b51f02-8198-40e8-9436-5c76814848b1\",\"screenshots@mozilla.org\":\"ad778eb2-f83a-4fec-bddb-7334b66021cb\",\"webcompat-reporter@mozilla.org\":\"91ae6b77-05c1-4f95-9160-5c03c81d7c17\",\"webcompat@mozilla.org\":\"4b13fac9-dae4-45db-8642-87a392b5d716\",\"default-theme@mozilla.org\":\"ab64967d-99c7-4c4b-b131-b746ed5de006\",\"google@search.mozilla.org\":\"2e92cc6b-73cc-4885-9cc9-9e62b74c2496\",\"amazondotcom@search.mozilla.org\":\"2c421447-d8df-4d6b-9cad-11aea5f77e52\",\"bing@search.mozilla.org\":\"1adc869f-e9ab-4313-b71a-238ee0dd89e4\",\"ddg@search.mozilla.org\":\"35412b43-f201-4907-8c56-fecca7a6c7bc\",\"ebay@search.mozilla.org\":\"8d628e68-94bc-4613-973c-8f981f599c6e\",\"twitter@search.mozilla.org\":\"01f8793e-6ec4-4cb4-9050-377faf1d73c8\",\"wikipedia@search.mozilla.org\":\"f212bbdc-c0bc-4893-92c5-0b880890dc2f\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1747776066);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1747773327);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20200602222727");
user_pref("media.gmp-manager.lastCheck", 1747773326);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1747776066);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "2e363d78-0bde-40bb-9253-737c7165af4d");
user_pref("security.sandbox.plugin.tempDirSuffix", "ef44c66b-c0b0-4a3e-a223-b40d0a9977bd");
user_pref("services.settings.clock_skew_seconds", 2103);
user_pref("services.settings.last_update_seconds", 1747776846);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1747776066);
user_pref("toolkit.startup.last_success", 1747775342);
user_pref("toolkit.telemetry.cachedClientID", "7c7cb187-4f01-4d52-a277-69af41a4e6d4");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
