// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1747775359);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1747778359);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1747775119);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1747774999);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1747774879);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1747775239);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1747774789);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1747775479);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 890880);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1747774729);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{db170490-2e96-4de8-9ecc-2b54d13406bb}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1747778411656");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1747780205656");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1747774733116");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1747796333116");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1747774731");
user_pref("browser.slowStartup.averageTime", 1149);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1747774730);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1747774731764");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "4d1ed6e033df4fda8143e5147a71ac99");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1747775359);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"49851ca6-328f-48af-b485-28826293f86f\",\"formautofill@mozilla.org\":\"d6e3a4cc-2c79-4f2a-b2aa-b082e391e011\",\"screenshots@mozilla.org\":\"aceb981a-613a-4c31-ba7e-115b3bedd7cb\",\"webcompat-reporter@mozilla.org\":\"d3c63952-0d01-4f05-8e6e-0d7def767b4c\",\"webcompat@mozilla.org\":\"7f756adc-6bb0-4486-9f20-4ba63a4a34ad\",\"default-theme@mozilla.org\":\"e0dd1bb8-7a8a-4fd8-8fa9-da23c77f91c8\",\"google@search.mozilla.org\":\"89d0d3be-88c7-4df9-a580-d1b2f724cea6\",\"amazondotcom@search.mozilla.org\":\"37b9b8f8-254c-4400-8fdc-213403c5d8e1\",\"bing@search.mozilla.org\":\"5ba58e2a-2746-4215-8558-86c88d92f4b9\",\"ddg@search.mozilla.org\":\"da5eb472-d6dc-4ce5-846f-4668efbc8538\",\"ebay@search.mozilla.org\":\"43eb5134-b2d7-42b5-9181-07e0f6e2ddc8\",\"twitter@search.mozilla.org\":\"4b1b6b32-6b60-4bfd-9174-32951817b0ca\",\"wikipedia@search.mozilla.org\":\"4c62decc-4497-437b-a53c-ce099ea0613e\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1747776066);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1747774816);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20200602222727");
user_pref("media.gmp-manager.lastCheck", 1747774815);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1747776066);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "fe50e4e1-db96-48ac-a539-017b8ed2d6cd");
user_pref("security.sandbox.plugin.tempDirSuffix", "e37b00b4-4497-47f6-9f2e-0816bdfa7449");
user_pref("services.settings.clock_skew_seconds", -2);
user_pref("services.settings.last_update_seconds", 1747776834);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1747776066);
user_pref("toolkit.startup.last_success", 1747774728);
user_pref("toolkit.telemetry.cachedClientID", "1ca7c5e4-ea45-48e3-bacc-78b3e1c37ea4");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
